---
title: "On-call Hours in ICU"
author: "AJ Clarkin"
date: "11/02/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```



```{r environment}

library(tidyverse)
library(here)
library(lubridate)
library(scales)
library(knitr)

```


```{r file-imports}

# To use this you need a CSV from the database. This will select the columns required.
# This will summarise the whole extract and use the earliest and latest dates as headers.


# note the squiffy null value

df <- read_csv(here("data_raw/feb22-aug22.csv"), na=c("\\0", "\\N"))
# glimpse(df)

```



```{r}
# summary(df)


df_trimmed <- df %>% 
  mutate(
    night1 = as_factor(night),
  ) %>% 
  select(rotadate, night1, time_night) %>% 
  mutate(n1 = fct_anon(night1))


# Group by consultant then count the total number of nights, the proportion filled in, and the average time of those completed

df_grp <-  df_trimmed %>% group_by(night1, n1) %>% 
  summarise(night_count = n(),
            response_rate = sum(!is.na(time_night)) / n(),
            avg_time = mean(time_night, na.rm = TRUE)
            ) %>% 
  mutate(hrs = as.integer(avg_time) / (60*60)) %>% 
  arrange(desc(hrs))


```




```{r get-dates}

startdate <- format(min(df_trimmed$rotadate), format = '%d-%m-%Y')
enddate <- format(max(df_trimmed$rotadate), format = '%d-%m-%Y')




```


## Hours Summary

These are the averaged consultant on-call hours between `r startdate` and `r enddate`.




```{r visualise-hours}

# Plot on the data on one chart with different geoms
#   - Bar chart for the values for each user
#   - Horizontal line for the mean
#   - Scatter for the percentage return rate of each consultant


p_labelled <- df_grp %>% ggplot(aes(x=reorder(night1, hrs))) +
  geom_bar(aes(y=hrs), stat="identity", fill="light blue") +
  geom_hline(yintercept = mean(df_grp$hrs, na.rm = TRUE)) +
  theme_light() +
  scale_y_continuous(breaks = c(2,4,6,8,10,12)) +
  ylab("Average Hours") +
  xlab("Consultant") +
  ggtitle(str_c("On-call Hours: ", startdate, " to ", enddate))
  

p_labelled



# New anonymous but using the consultant number
p_anon <- df_grp %>% ggplot(aes(x=reorder(n1, hrs))) +
  geom_bar(aes(y=hrs), stat="identity", fill="light blue") +
  geom_hline(yintercept = mean(df_grp$hrs, na.rm = TRUE)) +
  theme_light() +
  scale_y_continuous(breaks = c(2,4,6,8,10,12)) +
  ylab("Average Hours") +
  xlab("Consultant") +
  ggtitle(str_c("On-call Hours: ", startdate, " to ", enddate))
  

# p_anon



# Export the chart
img_filename <- str_c("on-call_hours_", startdate, "_", enddate, ".jpg")
ggsave(img_filename, path = here("images/"), plot = p_anon)

```

```{r demo-secondary-axis}

# If we wanted to include points with the percentage completion we could do the following
# Needs sec-axis() and it's not immediately clear which axis relates to which chart

# The points are being generated using geom_point()


# p_combined <- df_grp %>% ggplot(aes(x=reorder(night1, hrs))) +
#   geom_bar(aes(y=hrs), stat="identity", fill="light blue") +
#   geom_hline(yintercept = mean(df_grp$hrs, na.rm = TRUE)) +
#   geom_point(aes(y=response_rate*10), color="dark blue", size = 4) +
#   theme_light() +
#   scale_y_continuous(
#     breaks = c(2,4,6,8,10,12),
#     
#     # Second Axis
#     sec.axis = sec_axis(~.* 0.1,
#                         name = "Response Rate",
#                         labels = scales::percent,
#                         breaks = c(0.2, 0.4, 0.6, 0.8, 1))
#     
#     ) +
#   ylab("Average Hours") +
#   xlab("Consultant") +
#   ggtitle("On-call Hours - September 21 - February 22")
#   
# p_combined

```




```{r tabular-results}

df_nice <- df_grp %>%
  mutate(Completion = response_rate * 100,
         Hours = round(hrs, 1),) %>%
  rename(Consultant = night1,
         Nights = night_count,
         Consultant_No = n1) %>%
  select(-response_rate, -avg_time, -hrs)

kable(df_nice)

```


